CREATE TABLE oic (
    id NUMBER PRIMARY KEY GENERATED by default on null as IDENTITY,

    content CLOB,
    translation CLOB,
    cohere_embed vector(1024),

    application_name varchar2(256),
    author varchar2(256),
    content_type varchar2(256),
    creation_date varchar2(256),    
    date varchar2(256),    
    modified varchar2(256),    
    other1 varchar2(1024),    
    other2 varchar2(1024),    
    other3 varchar2(1024),    
    parsed_by varchar2(256),    
    filename varchar2(256),    
    path varchar2(1024),    
    publisher varchar2(256),    
    region varchar2(256),    
    summary CLOB,
    page number
);



